resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: jatindogra/sample_java
    configuration:
      integrationName: github
    initialVersion:
      sha: master

pipelines:
  - name: pipe_1
    setup:
      runtime:
        type: image
        image:
          custom:
            name: drydock/u16microbase
            tag: v7.2.4
      
    steps:
      - name: step1_A
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime:
            type: image
            image:
              auto:
                language: nodejs
        triggeredBy:
          resources:
            - gitrepo_res 
        execution:
          onExecute:
            - llk
