resources:
  - name: gitrepo_res_1
    type: gitRepo
    repoPath: BharathShippable/sample_java
    configuration:
      integrationName: bharath-shippable
    initialVersion:
      sha: master

pipelines:
  - name: pipe_1_1
    setup:
      runtime:
        type: image
        image:
          custom:
            name: drydock/u16microbase
            tag: v7.2.4
      
    steps:
      - name: step1
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime:
            type: image
            image:
              auto:
                language: nodejs
                version: v8.11.3
        triggeredBy:
          resources:
            - gitrepo_res_1
        execution:
          onExecute:
            - echo hi
            - printenv
